# Generated by Django 3.1.4 on 2020-12-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Book Title')),
                ('desc', models.CharField(max_length=128, verbose_name='Book Description')),
                ('author', models.CharField(max_length=64, verbose_name='Book Author')),
                ('pages', models.IntegerField(verbose_name='Book Pages')),
                ('price', models.FloatField(verbose_name='Book Price')),
                ('pub', models.CharField(max_length=64, verbose_name='Book Publication')),
                ('isbn', models.CharField(max_length=16, verbose_name='ISBN')),
                ('genre', models.CharField(max_length=32, verbose_name='Book Genre')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='User Name')),
                ('mail', models.CharField(max_length=64, verbose_name='User Email')),
                ('rollNo', models.CharField(max_length=16, verbose_name='Roll Number')),
                ('mobile', models.CharField(max_length=16, verbose_name='Mobile Number')),
                ('password', models.CharField(max_length=100, verbose_name='User Password')),
                ('authToken', models.CharField(max_length=50, verbose_name='Auth Token')),
            ],
        ),
    ]
